---
- hostname: localhost
  environment: DEV
  system: MySystem
- hostname: localhost
  environment: PROD
  system: MySystem
- hostname: localhost
  environment: PROD
  system: SystemWith404
- hostname: localhost
  environment: DEV
  system: SystemStatusRed
- hostname: localhost
  environment: DEV
  system: SystemStatusYellow
