---
- hostname: localhost
  environment: DEV
  system: SystemWithSimpleStatusCheck
- hostname: localhost
  environment: PROD
  system: SystemWithSimpleStatusCheck
- hostname: localhost
  environment: PROD
  system: SystemWith404
- hostname: localhost
  environment: DEV
  system: SystemStatusRed
- hostname: localhost
  environment: DEV
  system: SystemStatusYellow
- hostname: localhost
  environment: DEV
  system: ComplexSystemStatus
