---
- production
- prod
- live
- pre-live
- staging
- performance testing
- performance
- user acceptance testing
- acceptance testing
- uat
- testing
- test
- continuous integration
- ci
- development
- dev