---
- dev
- development
- ci
- continuous integration
- test
- testing
- uat
- acceptance testing
- user acceptance testing
- performance
- performance testing
- staging
- pre-live
- live
- prod
- production
